on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.stack
        key: v1-${{ hashFiles('zfoh.cabal', 'stack.yaml', 'stack.yaml.lock') }}
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-no-global: true
    - run: stack build --pedantic
    - run: stack exec zfoh build
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: _site
